# Generated by Django 6.0.6 on 2026-06-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='aboutme',
            field=models.TextField(blank=True, default='Your Description here', null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='email',
            field=models.EmailField(default='Your email', max_length=254),
        ),
        migrations.AlterField(
            model_name='hero',
            name='name',
            field=models.CharField(default='Your name', max_length=100),
        ),
        migrations.AlterField(
            model_name='hero',
            name='phone',
            field=models.CharField(default='Your number'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='profile',
            field=models.CharField(default='Your profie', max_length=100),
        ),
        migrations.AlterField(
            model_name='hero',
            name='role1',
            field=models.CharField(default='Role1', max_length=100),
        ),
        migrations.AlterField(
            model_name='hero',
            name='role2',
            field=models.CharField(default='Role2', max_length=100),
        ),
        migrations.AlterField(
            model_name='hero',
            name='role3',
            field=models.CharField(default='Role3', max_length=100),
        ),
    ]
