# Generated by Django 6.0.6 on 2026-06-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_hero_aboutme_alter_hero_email_alter_hero_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill1', models.CharField()),
                ('skillrate', models.CharField()),
            ],
        ),
        migrations.AlterField(
            model_name='hero',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='hero',
            name='name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='hero',
            name='phone',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='hero',
            name='profile',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='hero',
            name='role1',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='hero',
            name='role2',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='hero',
            name='role3',
            field=models.CharField(),
        ),
    ]
