# Generated by Django 6.0.6 on 2026-06-26 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_skills_alter_hero_email_alter_hero_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skills',
            old_name='skill1',
            new_name='skill',
        ),
    ]
