# Generated by Django 6.0.6 on 2026-06-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_skill1_skills_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='Address',
            field=models.CharField(default='Address'),
        ),
    ]
