# Generated by Django 6.0.6 on 2026-06-28 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_hero_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField()),
                ('years', models.CharField(default='From-to')),
                ('address', models.CharField()),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameofposition', models.CharField()),
                ('nameofcompany', models.CharField()),
                ('years', models.TextField()),
                ('address', models.CharField()),
                ('desc', models.CharField()),
            ],
        ),
        migrations.AddField(
            model_name='hero',
            name='summary',
            field=models.TextField(default='Summary about you'),
        ),
    ]
