# Generated by Django 6.0.6 on 2026-06-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_education_experience_hero_summary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='desc',
            new_name='desc1',
        ),
        migrations.AddField(
            model_name='experience',
            name='desc2',
            field=models.CharField(default='Description 2'),
        ),
        migrations.AddField(
            model_name='experience',
            name='desc3',
            field=models.CharField(default='Description 3'),
        ),
    ]
