# Generated by Django 6.0.6 on 2026-06-28 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='years',
            new_name='year',
        ),
    ]
