# Generated by Django 6.0.6 on 2026-07-02 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_name_education_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='image',
            field=models.ImageField(default='assets/img/person.png', upload_to=''),
        ),
    ]
