# Generated by Django 6.0.6 on 2026-07-02 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_hero_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='image',
            field=models.ImageField(default='assets/img/person.png', upload_to='profile_images/'),
        ),
    ]
